on:
  - push
  - workflow_dispatch

name: Update repository

jobs:
  build-packages:
    name: Build packages
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          #- azure-cli
          #- dotnet-core-bin
          - pass-git-helper
          #- j4-dmenu-desktop
          #- minecraft-launcher
          #- pulseaudio-ctl
    steps:
      - name: Clone package from AUR
        uses: mdarocha/run-in-archlinux-action@v1
        with:
          commands: |
            git clone https://aur.archlinux.org/${{ matrix.package }}.git package
      - name: Build package
        uses: mdarocha/run-in-archlinux-action@master
        with:
          commands: |
            cd package/
            makepkg -c -s
      - run: |
          find .

  deploy-to-azure:
    name: Push repository to Azure
    runs-on: ubuntu-latest
    steps:
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create repository database
        uses: mdarocha/run-in-archlinux-action@v1
        with:
          commands: |
            mkdir -p repository/
            ls -al
            echo "test from arch linux" > repository/file2

      - name: Upload repository to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name markarchrepo -d repo -s repository/

