on:
  - push
  - workflow_dispatch

name: Update repository

jobs:
  deploy-to-azure:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create test files
        run: |
          mkdir -p repository/
          echo "test file" > repository/file

      - name: Run script in Arch Linux
        uses: mdarocha/run-in-archlinux-action
        with:
          commands: |
            echo "test from arch linux" > repository/file2

      - name: Upload files
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name markarchrepo -d repo -s repository/

