on:
  - push
  - workflow_dispatch

name: Update repository

jobs:
  build-packages:
    name: Build packages
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          #- azure-cli
          #- dotnet-core-bin
          - pass-git-helper
          #- j4-dmenu-desktop
          #- minecraft-launcher
          #- pulseaudio-ctl
    steps:
      - uses: actions/checkout@v2
      - name: Build package
        uses: mdarocha/run-in-archlinux-action@v1
        with:
          commands: |
            ./scripts/build-package.sh ${{ matrix.package }}
      - uses: actions/upload-artifact@v2
        with:
          name: package-${{ matrix.package }}
          path: build/*

  deploy-to-azure:
    name: Push repository to Azure
    runs-on: ubuntu-latest
    needs: build-packages
    steps:
      - name: Download all built packages
        uses: actions/download-artifact@v2
        with:
          path: packages/
      - name: Create repository database
        uses: mdarocha/run-in-archlinux-action@v1
        with:
          commands: |
            mkdir -p repository/
            mv packages/*/* repository/
            repo-add repository/markarch.db.tar.xz repository/*
            find .
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Upload repository to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name markarchrepo -d repo -s repository/

