on:
  - push
  - workflow_dispatch

name: Update repository

jobs:
  build-packages:
    name: Build packages
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - aerc
          # - aseprite
          - azure-cli
          - datagrip
          - dotnet-core-bin
          - elm-bin
          - elm-language-server
          - fsharp-language-server
          - getmail
          # - godot
          - gzdoom
          - j4-dmenu-desktop
          - libpostal-git
          - minecraft-launcher
          - multimc5
          - neovim-git
          - osm2pgsql
          - pandoc-include-code
          - pass-git-helper
          - pulseaudio-ctl
          - spicetify-cli
          - spotify
          - unityhub
          - wev
          - words-pl
          - zmusic
    steps:
      - uses: actions/checkout@v2
      - name: Build package
        uses: mdarocha/run-in-archlinux-action@v1
        with:
          commands: |
            ./scripts/setup-gpg.sh "${{ secrets.GPG_SIGN_KEY }}"
            ./scripts/build-package.sh ${{ matrix.package }}
      - uses: actions/upload-artifact@v2
        with:
          name: package-${{ matrix.package }}
          path: build/*

  deploy-to-azure:
    name: Push repository to Azure
    runs-on: ubuntu-latest
    needs: build-packages
    steps:
      - uses: actions/checkout@v2
      - name: Download all built packages
        uses: actions/download-artifact@v2
        with:
          path: packages/
      - name: Create repository database
        uses: mdarocha/run-in-archlinux-action@v1
        with:
          commands: |
            ./scripts/setup-gpg.sh "${{ secrets.GPG_SIGN_KEY }}"
            mkdir -p repository/
            mv packages/*/* repository/
            find repository/ ! -name "*.sig" | xargs | repo-add --sign repository/markarch.db.tar.xz
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Upload repository to Azure Blob Storage
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob upload-batch --account-name markarchrepo -d repo -s repository/

